// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpVplvrn0SuLCiQbG4MpxLSqvaQpacpU',
    appId: '1:228058477502:web:a9c945ae197086b4f9bfef',
    messagingSenderId: '228058477502',
    projectId: 'face-b8de8',
    authDomain: 'face-b8de8.firebaseapp.com',
    storageBucket: 'face-b8de8.appspot.com',
    measurementId: 'G-DYQ8092YZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVosEcAOLps1Yd2AqN58MTWHWiChveqs',
    appId: '1:228058477502:android:189a1c68f23463e6f9bfef',
    messagingSenderId: '228058477502',
    projectId: 'face-b8de8',
    storageBucket: 'face-b8de8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqpJ_18xogvaTTWTdj24dHUogL-VILf8',
    appId: '1:228058477502:ios:beefab705d644bd7f9bfef',
    messagingSenderId: '228058477502',
    projectId: 'face-b8de8',
    storageBucket: 'face-b8de8.appspot.com',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqpJ_18xogvaTTWTdj24dHUogL-VILf8',
    appId: '1:228058477502:ios:beefab705d644bd7f9bfef',
    messagingSenderId: '228058477502',
    projectId: 'face-b8de8',
    storageBucket: 'face-b8de8.appspot.com',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzpVplvrn0SuLCiQbG4MpxLSqvaQpacpU',
    appId: '1:228058477502:web:4f4f51907220d2d0f9bfef',
    messagingSenderId: '228058477502',
    projectId: 'face-b8de8',
    authDomain: 'face-b8de8.firebaseapp.com',
    storageBucket: 'face-b8de8.appspot.com',
    measurementId: 'G-91JDBFS25K',
  );
}
